GET http://localhost:8000/api/user

###
POST  http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "username": "hhd0108",
    "password": "123456"
}

###
POST http://localhost:8000/api/login/login
Content-Type: application/json

{
    "username": "hhd",
    "password": "123456"
}